version: "3.1"
services:
    haproxy:
        build: ./haproxy/.
        ports:
             - '8080:8080'
        networks:
            - default
        links:
            - www
            - www1
    www:
        build: .
 #       ports: 
  #          - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    www1:
        build: .
 #       ports:
  #          - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default

    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
